export type HookConfig = { version?: number; hooks?: Record<string, unknown[]>; [key: string]: unknown };

const ownedCommands = new Set(
  ['composer', 'shell', 'tool', 'pretooluse'].map(name => `node ./.chio/hooks/${name}.mjs`),
);

/** Upgrade only the commands generated by this extension; retain other hooks. */
export function mergeHookConfig(existing: unknown, template: HookConfig): HookConfig {
  if (!existing || typeof existing !== 'object' || Array.isArray(existing)) {
    throw new Error('Existing hooks.json must be an object; it was left unchanged.');
  }
  const current = existing as HookConfig;
  if (current.version !== undefined && current.version !== 1) {
    throw new Error('Unsupported hooks.json version; it was left unchanged.');
  }
  if (current.hooks !== undefined && (!current.hooks || typeof current.hooks !== 'object' || Array.isArray(current.hooks))) {
    throw new Error('Existing hooks.json hooks must be an object; it was left unchanged.');
  }
  const hooks: Record<string, unknown[]> = {};
  for (const [event, definitions] of Object.entries(current.hooks ?? {})) {
    if (!Array.isArray(definitions)) throw new Error(`Invalid ${event} hook definitions; file left unchanged.`);
    const retained = definitions.filter(definition => !(
      definition && typeof definition === 'object' &&
      ownedCommands.has((definition as { command: string }).command)
    ));
    if (retained.length) hooks[event] = retained;
  }
  for (const [event, definitions] of Object.entries(template.hooks ?? {})) {
    hooks[event] = [...(hooks[event] ?? []), ...definitions];
  }
  return { ...current, version: 1, hooks };
}
